server.port: 8080

spring:
  application.name: gateway

spring.cloud.discovery:
  enabled: true
  client.simple.instances:
    weather-api:
    - instance-id: weather-api
      service-id: weather-api
      host: nodeagent
      port: 9090

spring.cloud.gateway:
  loadbalancer:
    use404: false
  routes:
  - id: openapi
    uri: http://nodeagent:${server.port}
    predicates:
    - Path=/v3/api-docs/**
    filters:
    - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
  - id: weather-api
    uri: lb://weather-api
    predicates:
    - Path=/weather/**
    filters:
    - RewritePath=/weather/(?<path>.*), /$\{path}

springdoc:
  packages-to-scan:
  - io.github.mavaze.weathermap
  api-docs:
    # path: /v3/api-docs
    enabled: true
  swagger-ui:
    # path: /restdocs.html
    use-root-path: true
    oauth:
      client-id: gateway
      client-secret: secret # ignored if pkce is enabled
      app-name: weather-cloud-gateway
      # use-pkce-with-authorization-code-grant: true
    oauth2-redirect-url: http://nodeagent:8080/webjars/swagger-ui/oauth2-redirect.html
  oauth-flow:
    authorization-url: http://nodeagent:9000/oauth2/authorize
    token-url: http://nodeagent:9000/oauth2/token

logging:
  level:
    root: DEBUG
    org.apache.tomcat.util.net.NioEndpoint: OFF
