server.port: 9000
spring:
  application.name: security

authorization.server.url: http://weather-cloud-security:${server.port}
gateway.server.url: http://weather-cloud-gateway:8080
weatherapi.server:
  host: weather-cloud-api
  port: 9090

# logging:
#   level:
#     root: DEBUG
#     org.apache.tomcat.util.net.NioEndpoint: OFF